### ISSUE TITLE
No matching distribution found for kittyfuzzer-remote

### ISSUE THREAD

**Issue by sh4d0wf4xx** [yformaggio/VxFuzz#1]
While installing the requirements, I get an error message for kittyfuzzer-remote
`ERROR: Could not find a version that satisfies the requirement kittyfuzzer-remote (from versions: none)`
`ERROR: No matching distribution found for kittyfuzzer-remote`

Any suggestions will be appreciated.

Thanks

**Comment by thelumberjhack** [comment]
Hey, I don't have time to dive into this issue at the moment. Quick question, have you looked at https://github.com/cisco-sas/kitty? 
It seems like `kittyfuzzer-remote` is now part of Kitty, but I am not sure about that. If you find a way to fix the error, feel free to do a PR.
Cheers

**Comment by sh4d0wf4xx** [comment]
Hej,

It appears `kittyfuzzer-remote` is no longer in use by kitty/katnip, and there's no other identifiable way of getting it right now.

Thanks for your time.

**Comment by thelumberjhack** [comment]
A quick look at the kitty repo and I found this example: https://github.com/cisco-sas/kitty/tree/master/examples/04_remote_controller looks like it could help.
I don't have the environment to try so I cannot confirm. And since I won't be able to maintain it, I am gonna archive it.
